# pylint: disable=all

from typing import Any

from ..supers import FXNode

class FXGroup(FXNode):
    def __init__(self, *nodes: FXNode) -> None: ...
    def add(self, node: FXNode) -> None: ...
    def remove(self, node: FXNode) -> None: ...
    def contains(self, node: FXNode) -> bool: ...
    def render(self, to: Any) -> None: ...
